### ISSUE TITLE
No Slash Command Options

### ISSUE THREAD

**Issue by QaisZAK** [HazimAr/Discord-Typescript-Boilerplate#13]
There is no possibility to add any Slash Command Options.

Currently the `SlashCommand` constructor only takes in a `name`, `description` and `{requiredPermissions}` as `options`
![code](https://user-images.githubusercontent.com/70582355/153618004-9f370046-8aa8-492c-b513-2b85fb0421ac.png)

**Comment by HazimAr** [comment]
Fixed in [https://github.com/HazimAr/Discord-Typescript-Boilerplate/commit/3458922cc2b56f603cc87b764e08dd091caf6068](here)
